name: 语雀 API 测试
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 测试语雀 API
        env:
          YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}
          NAMESPACE: "whhhhhhhhh-utetq"
        run: |
          curl -v -H "X-Auth-Token: $YUQUE_TOKEN" "https://www.yuque.com/api/v2/users/$NAMESPACE/repos"
